sudo: required
language: java

jdk:
  - oraclejdk8
  
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/caches/modules-2/files-2.1
  
before_install:
  - chmod +x gradlew
  - sudo apt-get -qq update
  - sudo apt-get install -y wine
  
before_script: cd de.peeeq.wurstscript

script:
  - ./gradlew assemble test --info